spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Iias1234@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    #  上传文件最大SIZE
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1024MB
  profiles:
    active: dev



audit:
  max-audit-level: 2
  callback-url: "https://callbacks.airbnb.com/v1/external/callback/hanclean/manual/review"
